<?php

/**
 * BaseJobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                         $name                                                Type: string(255), unique
 * @property Doctrine_Collection|JobeetJob[]                $JobeetJobs                                          
 * @property Doctrine_Collection|JobeetAffiliate[]          $JobeetAffiliates                                    
 * @property Doctrine_Collection|JobeetCategoryAffiliate[]  $JobeetCategoryAffiliate                             
 *  
 * @method string                                           getName()                                            Type: string(255), unique
 * @method Doctrine_Collection|JobeetJob[]                  getJobeetJobs()                                      
 * @method Doctrine_Collection|JobeetAffiliate[]            getJobeetAffiliates()                                
 * @method Doctrine_Collection|JobeetCategoryAffiliate[]    getJobeetCategoryAffiliate()                         
 *  
 * @method JobeetCategory                                   setName(string $val)                                 Type: string(255), unique
 * @method JobeetCategory                                   setJobeetJobs(Doctrine_Collection $val)              
 * @method JobeetCategory                                   setJobeetAffiliates(Doctrine_Collection $val)        
 * @method JobeetCategory                                   setJobeetCategoryAffiliate(Doctrine_Collection $val) 
 *  
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobeetCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetJob as JobeetJobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('JobeetAffiliate as JobeetAffiliates', array(
             'refClass' => 'JobeetCategoryAffiliate',
             'local' => 'category_id',
             'foreign' => 'affiliate_id'));

        $this->hasMany('JobeetCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}