<?php

/**
 * BaseJobeetAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                         $url                                                 Type: string(255)
 * @property string                                         $email                                               Type: string(255), unique
 * @property string                                         $token                                               Type: string(255)
 * @property bool                                           $is_active                                           Type: boolean
 * @property Doctrine_Collection|JobeetCategory[]           $JobeetCategories                                    
 * @property Doctrine_Collection|JobeetCategoryAffiliate[]  $JobeetCategoryAffiliate                             
 *  
 * @method string                                           getUrl()                                             Type: string(255)
 * @method string                                           getEmail()                                           Type: string(255), unique
 * @method string                                           getToken()                                           Type: string(255)
 * @method bool                                             getIsActive()                                        Type: boolean
 * @method Doctrine_Collection|JobeetCategory[]             getJobeetCategories()                                
 * @method Doctrine_Collection|JobeetCategoryAffiliate[]    getJobeetCategoryAffiliate()                         
 *  
 * @method JobeetAffiliate                                  setUrl(string $val)                                  Type: string(255)
 * @method JobeetAffiliate                                  setEmail(string $val)                                Type: string(255), unique
 * @method JobeetAffiliate                                  setToken(string $val)                                Type: string(255)
 * @method JobeetAffiliate                                  setIsActive(bool $val)                               Type: boolean
 * @method JobeetAffiliate                                  setJobeetCategories(Doctrine_Collection $val)        
 * @method JobeetAffiliate                                  setJobeetCategoryAffiliate(Doctrine_Collection $val) 
 *  
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobeetAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JobeetCategory as JobeetCategories', array(
             'refClass' => 'JobeetCategoryAffiliate',
             'local' => 'affiliate_id',
             'foreign' => 'category_id'));

        $this->hasMany('JobeetCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}