<?php

/**
 * BaseJobeetCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                      $category_id                             Type: integer, primary key
 * @property int                      $affiliate_id                            Type: integer, primary key
 * @property JobeetCategory           $JobeetCategory                          
 * @property JobeetAffiliate          $JobeetAffiliate                         
 *  
 * @method int                        getCategoryId()                          Type: integer, primary key
 * @method int                        getAffiliateId()                         Type: integer, primary key
 * @method JobeetCategory             getJobeetCategory()                      
 * @method JobeetAffiliate            getJobeetAffiliate()                     
 *  
 * @method JobeetCategoryAffiliate    setCategoryId(int $val)                  Type: integer, primary key
 * @method JobeetCategoryAffiliate    setAffiliateId(int $val)                 Type: integer, primary key
 * @method JobeetCategoryAffiliate    setJobeetCategory(JobeetCategory $val)   
 * @method JobeetCategoryAffiliate    setJobeetAffiliate(JobeetAffiliate $val) 
 *  
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobeetCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_category_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JobeetCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('JobeetAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}