<?php

/**
 * sfGuardUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserPermissionTable extends PluginsfGuardUserPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return sfGuardUserPermissionTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserPermission');
    }
}