generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_category
    with_doctrine_route:   true

    config:
      actions: ~
      fields:  ~
      list:    
        object_actions: {}
        batch_actions: {}
        title: Category Management
        display: [=name, slug]
      filter:  
        class: false
      form:    
        actions:
          _delete: ~
          _list:   ~
          _save:   ~
      edit:    
        title: Editing Category "%%name%%"
      new:     
        title: New Category
