dev:
  doctrine:
    class: sfDoctrineDatabase
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=prod_dbname'
      username: sebastian
      password: '123'
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jobeet_test'
      username: root
      password: null
