<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/06/09 02:15:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
